Rewrite into a single file.
It looses some options from `git-cache-control` but I may add them back
later. Most of the commands in there were done by moving into the cache
directory and invoking commands there. It can now be done with the
`cache` sub-command, e.g., `git cache @git.repo.org remote`.

It's better structured and hopefully more reliable. It will be easier to
extend as well since it works through a callback with anything prefixed
with `_gitc_` will get a call when invoking a sub-command.

For example, `git fetch` calls `_gitc_fetch` which updates the cache.

diff --git a/git-cached b/git-cached
--- a/git-cached
+++ b/git-cached
@@ -5,80 +5,165 @@ if [[ ! $GIT_CACHE_DIR ]]; then
   GIT_CACHE_DIR=$HOME/.git_cache
 fi
 
-if [[ $1 = 'clone' ]]; then
-  # The following variables will be set:
-  #   GIT_ADDR
-  #   GIT_PROT
-  #   GIT_DOMA
-  #   GIT_PATH
-  #   GIT_PROJ
-  #   GIT_USER
-  #   GIT_PORT
-  #   GIT_REPO
-  . git-cache-parse-url
-  [[ ! $GIT_ADDR ]] && echo "Could not detect a valid link." && exit
 
-  git-cache-repo $GIT_REPO $GIT_PROJ $GIT_ADDR
-  [[ ! -d $GIT_CACHE_DIR/$GIT_REPO ]] && echo "Error creating the cache repository." && exit
+# Helper functions.
+# ----------------------------------------------------------------------------
 
-  COMMAND=$1
-  shift
-  git $COMMAND --reference $GIT_CACHE_DIR/$GIT_REPO "$@"
+function __gitc_initialize() {
+  #                                      1 addr - full address
+  #                                      | 2 prot - protocol, e.g. http://, git://, etc...
+  #                                      | |                3 user - the user in user@git.drupal.org[...]
+  #                                      | |                |            4 doma - domain, e.g. git.drupal.org
+  #                                      | |                |            |              5 port - port number
+  #                                      | |                |            |              |              6 path - path after domain
+  #                                      | |                |            |              |              |              7 proj - project name
+  #                                      | |                |            |              |              |              |
+  local s=$(echo "~ $*"| sed -n 's|.*[ ]\(\([a-zA-Z]*://\)*\([^ ]*[@]\)*\([^ /:]*\)[:]*\([0-9]*\)*[/]*\([^ :]*[^ /]*/\([^ /]*\)\.git\)\).*|\1,\2,\3,\4,\5,\6,\7|p')
+  local addr=$(echo $s | sed -n 's|\([^,]*\),.*|\1|p')
+  local prot=$(echo $s | sed -n 's|\([^,]*,\)\{1\}\([^,]*\),.*|\2|p')
+  local user=$(echo $s | sed -n 's|\([^,]*,\)\{2\}\([^,@]*\)[@]*,.*|\2|p')
+  local doma=$(echo $s | sed -n 's|\([^,]*,\)\{3\}\([^,]*\),.*|\2|p')
+  local port=$(echo $s | sed -n 's|\([^,]*,\)\{4\}\([^,]*\),.*|\2|p')
+  local path=$(echo $s | sed -n 's|\([^,]*,\)\{5\}\([^,]*\),.*|\2|p')
+  local proj=$(echo $s | sed -n 's|\([^,]*,\)\{6\}\([^,]*\)|\2|p')
+  local repo=
+  local cdir=
+  local cwd=`pwd`
 
-elif [[ $1 = 'repair' ]] || [[ $1 = 'no-cache' ]]; then
-  # Need to find remote info.
-  . git-cache-parse-url $( git remote show -n origin | sed -n 's|\([ ]*Fetch[ ]*URL:[ ]*.*\.git\).*|\1|p' )
-  [[ ! $GIT_ADDR ]] && echo "Could not find the fetch URL." && exit
-
-  # Look for the alternates file relative to the working directory.
-  git_root=`pwd`
-  while [[ $git_root != '/' ]] && [[ ! -d "$git_root/.git" ]]; do
-    git_root=$( dirname $git_root )
-  done
-  alternates=$git_root/.git/objects/info/alternates
-  [[ ! -f $alternates ]] && echo "Could not find the alternates file." && exit
-
-  if [[ $1 = 'repair' ]]; then
-    
-    # Must have an existing entry with the same pattern.
-    if [[ ! $( sed -n "\|^.*/$GIT_REPO/objects$|p" "$alternates" ) ]]; then
-      echo "The local repository is not cached. I cannot repair it." && exit
-    fi
-    repaired=false
-
-    # Generate the cache repo if it doesn't exist.
-    if [[ ! -d $GIT_CACHE_DIR/$GIT_REPO ]]; then
-      git-cache-repo $GIT_REPO $GIT_PROJ $GIT_ADDR
-      repaired=true
-    fi
-
-    # Modify alternates so it points to the correct cache directory. It only
-    # changes lines specific to this caching scipts. Other alternates that may
-    # have been added manually will remain unchanged even if it contains a bad
-    # pointer.
-    if [[ ! $( sed -n "\|^$GIT_CACHE_DIR/$GIT_REPO/objects$|p" "$alternates" ) ]]; then
-      # Fix object pointer. An 'alternates.bak' will be created.
-      sed -i.bak "s|^.*/$GIT_REPO/objects$|$GIT_CACHE_DIR/$GIT_REPO/objects|" "$alternates"
-      repaired=true
-      echo "Alternates now pointing to the cache objects in $GIT_REPO."
-    fi
-
-    [[ $repaired == false ]] && echo "There is nothing to repair."
-
-  elif [[ $1 = 'no-cache' ]]; then
-
-    # Make sure it is pointing to a cache repo.
-    if [[ $( sed -n "\|^$GIT_CACHE_DIR/$GIT_REPO/objects$|p" "$alternates" ) ]]; then
-      echo "Repacking..."
-      git repack -a -f -d
-      # Remove object pointer. An 'alternates.bak' will be created.
-      sed -i.bak "s|^$GIT_CACHE_DIR/$GIT_REPO/objects$||" "$alternates"
-    else
-      echo "The local repository is not cached."
-    fi
+  if [[ $doma ]]; then
+    repo=@$doma
+    cdir=$GIT_CACHE_DIR/$repo
+  else
+    echo "Could not determine the url for the repository." && exit
   fi
 
-else
-  # Pass through other commands.
+  # Create cache directory for the domain and initialize if it doesn't exist.
+  if [[ ! -d  $cdir ]]; then
+    mkdir $cdir && cd $cdir
+    git init --bare
+    # Remove the initialized repo on failure.
+    # 1/SIGHUP, 2/SIGINT, 3/SIGQUIT, 15/SIGTERM, ERR
+    trap "rm -Rf $cdir && cd $cwd" 1 2 3 15 ERR
+  else
+    cd $cdir
+  fi
+
+  # If the remote doesn't exist locally, then initialize.
+  if [[ ! $( git remote | sed -n "/^${proj}$/p" ) ]]; then
+    # Create a temporary directory.
+    if [[ -d $TMPDIR ]]; then
+      TEMPDIR=`mktemp -d -t $proj`
+    else
+      TEMPDIR=`mktemp -d`
+    fi
+    trap "rm -Rf $TEMPDIR && cd $cwd" EXIT
+
+    # Clone project and use as a remote in the reference cache.
+    echo "Initializing clone of $proj from $repo..."
+    git clone --bare $addr $TEMPDIR
+    git remote add $proj $TEMPDIR
+
+    # Update with temporary local remote then point remote URL externally.
+    # Secondary fetch registers external remote in FETCH_HEAD.
+    echo "Creating cache: $repo >> $proj..."
+    git remote update $proj
+    git remote set-url $proj $addr
+    git fetch $proj --tags
+  fi
+
+  cd $cwd
+
+  git config --replace-all git-cached.project $proj
+  git config --replace-all git-cached.repository $repo
+  git config --replace-all git-cached.cache-dir $cdir
+}
+
+function __gitc_alternates() {
+  echo "`git rev-parse --show-toplevel`/.git/objects/info/alternates"
+}
+
+function __gitc_is_cached() {
+  __gitc_cache_dir
+}
+
+function __gitc_cache_dir() {
+  git config -z --get git-cached.cache-dir 2> /dev/null
+}
+
+function __gitc_project() {
+  git config -z --get git-cached.project 2> /dev/null
+}
+
+
+# Callback functions.
+# ----------------------------------------------------------------------------
+
+function _gitc_fetch() {
+  local cwd=`pwd`
+  local cdir=`__gitc_cache_dir`
+  local proj=`__gitc_project`
+
+  if [[ -d $cdir && -n $proj ]]; then
+    cd $cdir
+    echo "Fetching cache..." && git fetch $proj
+    cd $cwd
+  fi
   git "$@"
-fi
+}
+
+function _gitc_pull() {
+  _gitc_fetch "$@"
+}
+
+function _gitc_clone() {
+  __gitc_initialize "$@"
+
+  local cdir=`__gitc_cache_dir`
+
+  git "$@" --reference $cdir
+}
+
+function _gitc_cache_attach() {
+  [[ -n `__gitc_is_cached` ]] && echo "Already attached." && exit
+
+  __gitc_initialize `git config --get remote.origin.url`
+
+  local cdir=`__gitc_cache_dir`
+  local alts=`__gitc_alternates`
+
+  # Point to cached object dir inside the alternates file.
+  echo $cdir/objects >> $alts
+  echo "Taking out the garbage..." && git gc
+}
+
+function _gitc_cache_detach() {
+  [[ -z `__gitc_is_cached` ]] && echo "Nothing to detach." && exit
+
+  local cdir=`__gitc_cache_dir`
+  local alts=`__gitc_alternates`
+
+  echo "Repacking..." && git repack -adF
+  # Remove object pointer. An 'alternates.bak' will be created.
+  sed -i.bak "s|^$cdir/objects$||" $alts
+  git config -z --remove-section git-cached 2> /dev/null
+}
+
+function _gitc_cache_repair() {
+  echo "Repairing..." && _gitc_cache_detach && _gitc_cache_attach
+}
+
+function _gitc_cache() {
+  local cwd=`pwd`
+  local cdir=$GIT_CACHE_DIR/$2
+  if [[ -d $cdir ]]; then
+    shift 2 && cd $cdir && git "$@" && cd $cwd
+  else
+    echo "$2 does not exist."
+  fi
+}
+
+# Callback
+# ----------------------------------------------------------------------------
+# Detect callback function and fallback to git if it doesn't exist.
+__callback="_gitc_${1//-/_}"
+[[ `declare -Ff $__callback` ]] && $__callback "$@" || git "$@"
